### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by wenh06** [limbo018/DREAMPlace#208]
Branch: master
Hash: [ec18f9e](https://github.com/limbo018/DREAMPlace/commit/ec18f9eb234e06b207588f088bfe0ad4afa034f4)
Build environment: docker + GitHub action

Dockerfile:
```docker
FROM pytorch/pytorch:1.7.1-cuda11.0-cudnn8-devel
# FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

ARG PYPI_TUNA=1

LABEL maintainer="Yibo Lin <yibolin@pku.edu.cn>"

# Rotates to the keys used by NVIDIA as of 27-APR-2022.
RUN rm /etc/apt/sources.list.d/cuda.list 2>/dev/null || true
RUN rm /etc/apt/sources.list.d/nvidia-ml.list 2>/dev/null || true

RUN apt-get update && apt-get install -y gnupg

RUN apt-key del 7fa2af80
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub


# Installs system dependencies.
RUN apt-get update \
        && apt-get install -y \
            flex \
            libcairo2-dev \
            libboost-all-dev 


# Installs system dependencies from conda.
RUN conda install -y -c conda-forge bison

# Installs cmake.
ADD https://cmake.org/files/v3.21/cmake-3.21.0-linux-x86_64.sh /cmake-3.21.0-linux-x86_64.sh
RUN mkdir /opt/cmake \
        && sh /cmake-3.21.0-linux-x86_64.sh --prefix=/opt/cmake --skip-license \
        && ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake \
        && cmake --version

# Installs python dependencies.
RUN if [ "$PYPI_TUNA" = "1" ]; then \
        pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple; \
        fi
RUN pip install \
        pyunpack>=0.1.2 \
        patool>=1.12 \
        matplotlib>=2.2.2 \
        cairocffi>=0.9.0 \
        pkgconfig>=1.4.0 \
        setuptools>=39.1.0 \
        scipy>=1.1.0 \
        numpy>=1.15.4 \
        shapely>=1.7.0

# Installs dreamplace.
RUN mkdir -p /DREAMPlace
WORKDIR /DREAMPlace
COPY . /DREAMPlace
RUN mkdir -p build install
WORKDIR /DREAMPlace/build
RUN cmake .. -DCMAKE_INSTALL_PREFIX=../install -DPython_EXECUTABLE=$(which python)
RUN make
RUN make install
# RUN ln -s /DREAMPlace/build/install/bin/dreamplace /usr/local/bin/dreamplace

WORKDIR /DREAMPlace
```

GitHub action config:
```yml
name: Docker Image CI and Test (optional)

on:
  push:
    branches: [ docker-ci ]
  pull_request:
    branches: [ master ]

env:
  # see the Dockerfile for the definition of some of the following environment variables
  docker_main_filename: Dockerfile
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_HUB_REPOSITORY: dreamplace
  DOCKER_IMAGE_TAG: cuda

jobs:

  build:
    if: contains(fromJson('["wenh06"]'), github.repository_owner)

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Clear unnecessary system components
      run: |
        echo "Free space before cleanup:"
        df -h
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        echo "Free space after cleanup:"
        df -h
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push (optional) the Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ env.docker_main_filename }}
        push: false
        # load: true
        build-args: |
          PYPI_TUNA=0
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
```

Error message:
```text
#26 512.9 cd /DREAMPlace/build/dreamplace/ops/place_io && /usr/bin/c++ -DDRAWPLACE=1 -DENABLE_CUDA=0 -DTORCH_EXTENSION_NAME=place_io_cpp -DTORCH_VERSION_MAJOR=1 -DTORCH_VERSION_MINOR=7 -D_GLIBCXX_USE_CXX11_ABI=0 -Dplace_io_cpp_EXPORTS -I/DREAMPlace/thirdparty/flute -I/DREAMPlace/thirdparty/OpenTimer -I/DREAMPlace/dreamplace/ops/place_io/.. -I/DREAMPlace/thirdparty/Limbo -I/usr/include/cairo -isystem /DREAMPlace/thirdparty/pybind11/include -isystem /opt/conda/include/python3.8 -isystem /opt/conda/lib/python3.8/site-packages/torch/include -isystem /opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -O3 -DNDEBUG -fPIC -fvisibility=hidden -flto -fno-fat-lto-objects -D_GLIBCXX_USE_CXX11_ABI=0 -fopenmp -std=gnu++1z -MD -MT dreamplace/ops/place_io/CMakeFiles/place_io_cpp.dir/src/PlaceDB.cpp.o -MF CMakeFiles/place_io_cpp.dir/src/PlaceDB.cpp.o.d -o CMakeFiles/place_io_cpp.dir/src/PlaceDB.cpp.o -c /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp: In member function 'virtual void DreamPlace::PlaceDB::add_def_pin(const DefParser::Pin&)':
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:396:17: error: 'const struct DefParser::Pin' has no member named 'vPinPort'
#26 515.6    } else if (!p.vPinPort.empty()) {
#26 515.6                  ^~~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:398:35: error: 'const struct DefParser::Pin' has no member named 'vPinPort'
#26 515.6      for (std::size_t i = 0; i < p.vPinPort.size(); ++i) {
#26 515.6                                    ^~~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:400:14: error: 'const struct DefParser::Pin' has no member named 'vPinPort'
#26 515.6        if (!p.vPinPort[i].vLayer.empty()) {
#26 515.6               ^~~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:431:17: error: 'const struct DefParser::Pin' has no member named 'vPinPort'
#26 515.6    } else if (!p.vPinPort.empty()) {
#26 515.6                  ^~~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:432:22: error: 'const struct DefParser::Pin' has no member named 'vPinPort'
#26 515.6      node.setOrient(p.vPinPort.front().orient);
#26 515.6                       ^~~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:461:19: error: 'const struct DefParser::Pin' has no member named 'vPinPort'
#26 515.6      } else if (!p.vPinPort.empty()) {
#26 515.6                    ^~~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:462:37: error: 'const struct DefParser::Pin' has no member named 'vPinPort'
#26 515.6        for (std::size_t i = 0; i < p.vPinPort.size(); ++i) {
#26 515.6                                      ^~~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:463:20: error: 'PinPort' is not a member of 'DefParser'
#26 515.6          DefParser::PinPort const& pport = p.vPinPort[i];
#26 515.6                     ^~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:464:37: error: 'pport' was not declared in this scope
#26 515.6          for (std::size_t j = 0; j < pport.vLayer.size(); ++j) {
#26 515.6                                      ^~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:464:37: note: suggested alternative: 'qsort'
#26 515.6          for (std::size_t j = 0; j < pport.vLayer.size(); ++j) {
#26 515.6                                      ^~~~~
#26 515.6                                      qsort
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:557:17: error: 'const struct DefParser::Pin' has no member named 'vPinPort'
#26 515.6    } else if (!p.vPinPort.empty()) {
#26 515.6                  ^~~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:558:35: error: 'const struct DefParser::Pin' has no member named 'vPinPort'
#26 515.6      for (std::size_t i = 0; i < p.vPinPort.size(); ++i) {
#26 515.6                                    ^~~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:562:18: error: 'PinPort' is not a member of 'DefParser'
#26 515.6        DefParser::PinPort const& pport = p.vPinPort[i];
#26 515.6                   ^~~~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:563:35: error: 'pport' was not declared in this scope
#26 515.6        for (std::size_t j = 0; j < pport.vLayer.size(); ++j) {
#26 515.6                                    ^~~~~
#26 515.6 /DREAMPlace/dreamplace/ops/place_io/src/PlaceDB.cpp:563:35: note: suggested alternative: 'qsort'
#26 515.6        for (std::size_t j = 0; j < pport.vLayer.size(); ++j) {
#26 515.6                                    ^~~~~
#26 515.6                                    qsort
#26 516.9 make[2]: *** [dreamplace/ops/place_io/CMakeFiles/place_io_cpp.dir/src/PlaceDB.cpp.o] Error 1
#26 516.9 dreamplace/ops/place_io/CMakeFiles/place_io_cpp.dir/build.make:190: recipe for target 'dreamplace/ops/place_io/CMakeFiles/place_io_cpp.dir/src/PlaceDB.cpp.o' failed
#26 516.9 make[2]: Leaving directory '/DREAMPlace/build'
#26 516.9 CMakeFiles/Makefile2:3863: recipe for target 'dreamplace/ops/place_io/CMakeFiles/place_io_cpp.dir/all' failed
#26 516.9 make[1]: *** [dreamplace/ops/place_io/CMakeFiles/place_io_cpp.dir/all] Error 2
```

**Comment by limbo018** [comment]
You need update the submodules like Limbo.

**Comment by wenh06** [comment]
> You need to update the submodules like Limbo.

Yes, the submodules are up-to-date. I set
```yml
    - uses: actions/checkout@v4
      with:
        submodules: recursive
```
in the action file.
